// <auto-generated />
namespace HRONLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class emplWorkflow21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emplWorkflow21));
        
        string IMigrationMetadata.Id
        {
            get { return "201704272014001_emplWorkflow21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
