// <auto-generated />
namespace HRONLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class emplNotes_identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emplNotes_identity));
        
        string IMigrationMetadata.Id
        {
            get { return "201707041618360_emplNotes_identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
